In [14]:



import numpy as np

# Assume predictions is a list of NumPy arrays
predictions = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]

# Initialize an empty NumPy array to hold the stacked predictions

# Iterate over each prediction in the list
for pred in predictions:
    # Iterate over each item in the prediction
    for item in pred:
        # Read out the item and print it
        # Stack the item onto the stacked_predictions array
        stacked_predictions = np.stack((stacked_predictions, item))

# Print the stacked_predictions array
print(stacked_predictions)



TypeError: dispatcher for __array_function__ did not return an iterable

In [10]:
predictions = np.array([p for preds in predictions for p in preds])
predictions

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
arrays
np.stack(arrays, axis=0)

array([[[-1.22916233, -1.19664032, -0.2871838 , -1.76695366],
        [ 0.55474523,  0.16582134,  1.37072071, -0.18084245],
        [ 1.45691799,  0.21966465,  1.61233899, -0.15582648]],

       [[ 0.06659779, -0.01718159, -0.08468957, -0.47830176],
        [-0.90817866,  1.62561358, -2.44274681,  0.36253519],
        [ 1.07161848, -0.3055049 , -0.68675006,  0.82899754]],

       [[ 1.16152562, -0.73001184, -0.16354553,  0.65120017],
        [-1.27620949,  0.42760993, -0.34617792,  1.10055461],
        [ 0.3427059 , -0.74433675, -0.2751823 ,  1.04821617]],

       [[ 1.06044794, -0.37902728,  0.57194923, -0.88990431],
        [ 0.20716499,  0.00661651, -0.70965512,  0.35559397],
        [-0.68683461, -0.86439604,  1.10948279,  0.02429294]],

       [[ 0.85960144, -0.28394157, -0.19985958,  1.11659572],
        [ 1.4355031 ,  0.1797667 ,  0.11016269,  1.06464251],
        [-2.26818948,  1.83888105,  2.11722335, -0.84465823]],

       [[-0.3370108 ,  0.50161394, -0.26776149, -0.19304799]

In [17]:
arrays

[array([[-1.22916233, -1.19664032, -0.2871838 , -1.76695366],
        [ 0.55474523,  0.16582134,  1.37072071, -0.18084245],
        [ 1.45691799,  0.21966465,  1.61233899, -0.15582648]]),
 array([[ 0.06659779, -0.01718159, -0.08468957, -0.47830176],
        [-0.90817866,  1.62561358, -2.44274681,  0.36253519],
        [ 1.07161848, -0.3055049 , -0.68675006,  0.82899754]]),
 array([[ 1.16152562, -0.73001184, -0.16354553,  0.65120017],
        [-1.27620949,  0.42760993, -0.34617792,  1.10055461],
        [ 0.3427059 , -0.74433675, -0.2751823 ,  1.04821617]]),
 array([[ 1.06044794, -0.37902728,  0.57194923, -0.88990431],
        [ 0.20716499,  0.00661651, -0.70965512,  0.35559397],
        [-0.68683461, -0.86439604,  1.10948279,  0.02429294]]),
 array([[ 0.85960144, -0.28394157, -0.19985958,  1.11659572],
        [ 1.4355031 ,  0.1797667 ,  0.11016269,  1.06464251],
        [-2.26818948,  1.83888105,  2.11722335, -0.84465823]]),
 array([[-0.3370108 ,  0.50161394, -0.26776149, -0.19304799]